# Generated by Django 6.0.1 on 2026-03-28 06:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=cloudinary.models.CloudinaryField(default='default_img', max_length=255, verbose_name='image'),
        ),
    ]
